export default {
  'en-us': {
    barText: 'Blog',
    postsTitle: 'All posts',
    list: [
      {
        title: 'The first blog',
        author: 'author1',
        dateStr: 'May 12nd，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog1.html',
      },
      {
        title: 'The second blog',
        author: 'author2',
        dateStr: 'May 2nd，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog2.html',
      },
      {
        title: 'The third blog',
        author: 'author3',
        dateStr: 'April 25th，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog3.html',
      },
      {
        title: 'The forth blog',
        author: 'author4',
        dateStr: 'April 22nd，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog4.html',
      },
      {
        title: 'The fifth blog',
        author: 'author5',
        dateStr: 'April 22nd，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog5.html',
      },
      {
        title: 'The sixth blog',
        author: 'author6',
        dateStr: 'April 22nd，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog6.html',
      },
      {
        title: 'The seventh blog',
        author: 'author7',
        dateStr: 'April 22nd，2018',
        desc: 'Blog description, some text to sum up the main content of the blog',
        link: '/en-us/blog/blog7.html',
      },
    ],
  },
  'zh-cn': {
    barText: '精彩美文',
    postsTitle: '所有文章',
    list: [
      {
        title: '2018世界人工智能峰会总结',
        author: '钱猛',
        dateStr: 'May 12nd，2018',
        desc: '带你回顾2018世界人工智能峰会',
        link: '/zh-cn/blog/blog1.html',
      },
      {
        title: '2018云栖大会总结',
        author: '钱猛',
        dateStr: 'May 2nd，2018',
        desc: '带你回顾2018云栖大会',
        link: '/zh-cn/blog/blog2.html',
      },
      {
        title: '2018中国人工智能峰会总结',
        author: '钱猛',
        dateStr: 'April 25th，2018',
        desc: '带你回顾2018中国人工智能峰会',
        link: '/zh-cn/blog/blog3.html',
      },
      {
        title: '2018中国人工智能峰会总结',
        author: '钱猛',
        dateStr: 'April 22nd，2018',
        desc: '带你回顾2018中国人工智能峰会',
        link: '/zh-cn/blog/blog4.html',
      },
      {
        title: 'Android 高级面试题及答案',
        author: '钱猛',
        dateStr: 'April 22nd，2018',
        desc: 'Android面试经常会被问到的问题，记得收藏哦',
        link: '/zh-cn/blog/blog5.html',
      },
      {
        title: 'Python 面试问答 Top 25',
        author: '钱猛',
        dateStr: 'April 22nd，2018',
        desc: 'Python面试经常会被问到的问题，记得收藏哦',
        link: '/zh-cn/blog/blog6.html',
      },
      {
        title: 'Matlab实时监控股票交易数据之Timer函数应用实例',
        author: '钱猛',
        dateStr: 'April 22nd，2018',
        desc: 'Matlab处理股票交易定时应如何处理',
        link: '/zh-cn/blog/blog7.html',
      },
    ],
  },
};
